// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF4Yx1YJ6b25qQ4h0Rl9ATlM_JpJuYdGI',
    appId: '1:925196427803:web:986d1c68f7e06503b58ebe',
    messagingSenderId: '925196427803',
    projectId: 'notes-b5679',
    authDomain: 'notes-b5679.firebaseapp.com',
    storageBucket: 'notes-b5679.appspot.com',
    measurementId: 'G-MP438LX3FD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAopPAPNN3dRECJMFPsAZo12YqsOG9L-O8',
    appId: '1:925196427803:android:dd7ff4c27d86b8edb58ebe',
    messagingSenderId: '925196427803',
    projectId: 'notes-b5679',
    storageBucket: 'notes-b5679.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHtui_ccA5clV-CoFT3oQ8aH86WaEfdsA',
    appId: '1:925196427803:ios:ab54fbc336ef8586b58ebe',
    messagingSenderId: '925196427803',
    projectId: 'notes-b5679',
    storageBucket: 'notes-b5679.appspot.com',
    iosClientId: '925196427803-7mo3m11m1o0ea9361mljsvrrdmq5t5ep.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHtui_ccA5clV-CoFT3oQ8aH86WaEfdsA',
    appId: '1:925196427803:ios:ab54fbc336ef8586b58ebe',
    messagingSenderId: '925196427803',
    projectId: 'notes-b5679',
    storageBucket: 'notes-b5679.appspot.com',
    iosClientId: '925196427803-7mo3m11m1o0ea9361mljsvrrdmq5t5ep.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );
}
